set -g prefix C-a

set -g base-index 1
setw -g pane-base-index 1

set-option -g renumber-windows on

set -g status-style "bg=#2a273f,fg=#e0def4"
set -g status-left "#[fg=#9ccfd8] #S "
set -g window-status-current-style "bg=#393552,fg=#e0def4"
set -g window-status-style "bg=#2a273f,fg=#6e6a86"
